language: java
jdk:
  - oraclejdk8
install:
  - mvn clean install -DskipTests=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
cache:
  directories:
  - $HOME/.m2
sudo: false
