http.mappers.json-pretty-print: true
error.whitelabel.enabled: false

server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 0

---
spring.profiles: default

spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:"
  jpa:
    database: H2
    generate-ddl: true
    hibernate.ddl-auto: create-drop

---
spring.profiles: dev-persistent

spring:
  datasource:
    platform: h2
    url: jdbc:h2:./devdb
  jpa:
    database: H2
    generate-ddl: true
    hibernate.ddl-auto: create-drop

---
spring.profiles: test

server:
  port: 0
  address: 127.0.0.1
  sessionTimeout: 0

management.port: -1

spring:
  main:
    show-banner: false
    log-startup-info: true
  datasource:
    platform: h2
    url: "jdbc:h2:mem:"
  jpa:
    database: H2
    generate-ddl: true
    hibernate.ddl-auto: create-drop

---
spring.profiles: heroku

server.port: ${PORT}
server.address: 0.0.0.0

spring:
  main:
    web-environment: true
    show-banner: false
    log-startup-info: false
#  datasource:
#    url: ${DATABASE_URL}
#    platform: postgresql
#    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate.ddl-auto: none
